DATA_DIR: C:/Users/USER/high_density_sleep/data
METADATA_FILE_NAME: "Details information for healthy subjects.csv"
OUTPUT_DIR: 'all_electrodes_30' # add "select_channels" to run compact version

select_channels: None # ["F3", "F4", "C3", "C4", "O1", "O2"] # set None to select all None #
window_length: 30 # in seconds
step_size: 30   # in seconds
batch_size: 2000 # in epochs adjust to computer memory capacity
n_jobs: 8
overright: False

emg_channels:
  - "CHEMG1"
  - "CHEMG2"
  - "RLEG-"
  - "RLEG+"
  - "LLEG-"
  - "LLEG+"
eog_channels:
  - "EOG2"
  - "EOG1"
ecg_channels:
  - "ECG2"
  - "ECG1"

clean_non_eeg_channels:
  - "EOG2"
  - "EOG1"
  - "CHEMG"
  - "RLEG"
  - "LLEG"
  - "ECG"

METADATA_COLUMNS:
  - "time"
  - "stage"
  - "time_from_onset"
  - "epoch_length"
  - "num"
  - "patient"


DEMOGRAPHIC_AND_SLEEP_MEASURES:
  - "Age"
  - "Sex"
  - "TST(min)"
  - "WASO(min)"
  - "SE(%TRT)"
  - "SOL(min)"
  - "REML(min)"
  - "N1(min)"
  - "N2(min)"
  - "N3(min)"
  - "R(min)"

valid_sleep_stages:
  - "W"
  - "N1"
  - "N2"
  - "N3"
  - "R"

stage_color_map:
  "W":  "orange"
  "R":  "darkred"
  "N1": "magenta"
  "N2": "royalblue"
  "N3": "midnightblue"

state_color_map_pca_4_all:
  "0 (W)": "darkorange"
  "3 (W)": "salmon"
  "6 (R)": "red"
  "5 (N1)": "magenta"
  "2 (N2)": "royalblue"
  "4 (N3)": "midnightblue"
  "1 (N3)": "navy"


state_color_map_ica_4_all:
  "10 (W)": "orange"
  "5 (W)": "lightsalmon"
  "6 (W)": "lightcoral"
  "9 (N1)": "magenta"
  "7 (R)": "darkred"
  "1 (R)":  "red"
  "0 (N2)": "lightsteelblue"
  "8 (N2)": "royalblue"
  "4 (N2)": "mediumblue"
  "3 (N2)": "darkslateblue"
  "2 (N3)": "midnightblue"

state_color_map_ica_4_six:
  "6 (W)": "orange"
  "5 (W)": "lightsalmon"
  "2 (W)": "lightcoral"
  "11 (N1)": "magenta"
  "10 (R)": "darkred"
  "4 (R)":  "red"
  "0 (N2)": "mediumpurple"
  "1 (N2)": "violet"
  "7 (N2)": "lightsteelblue"
  "9 (N2)": "royalblue"
  "8 (N2)": "mediumblue"
  "12 (N3)": "darkslateblue"
  "3 (N3)": "midnightblue"


sleep_stage_plot_values:
  "W": 5
  "R": 4
  "N1": 3
  "N2": 2
  "N3": 1

sleep_stage_hypno_values:
  "W": 0
  "R": 4
  "N1": 1
  "N2": 2
  "N3": 3
  "L": -1

bands:
  "low_delta": [0.5, 1.5]
  "high_delta": [1, 4]
  "theta": [4, 8]
  "alpha": [8, 12]
  "low_sigma": [10, 13]
  "high_sigma": [12, 16]
  "beta": [15, 25]
  "gamma": [25, 40]

min_ex: 0.02 # the minimal explained variance ratio to keep in the pcs

eeg_name_map:
  low_delta_power: "Slow waves"
  high_delta_power: "Delta"
  theta_power: "Theta"
  alpha_power: "Alpha"
  low_sigma_power: "Low sigma"
  high_sigma_power: "High sigma"
  beta_power: "Beta"
  gamma_power: "Gamma"
  log_low_delta_power: "Slow waves \n(log)"
  log_high_delta_power: "Delta \n(log)"
  log_theta_power: "Theta \n(log)"
  log_alpha_power: "Alpha \n(log)"
  log_low_sigma_power: "Low sigma \n(log)"
  log_high_sigma_power: "High sigma \n(log)"
  log_beta_power: "Beta \n(log)"
  log_gamma_power: "Gamma \n(log)"
  spectral_intercept: "Intercept"
  spectral_slope: "Slope"
  spectral_entropy: "Entropy"
  root_total_power: "Power"

non_eeg_name_map:
  EOG:
    EOG_horizontal_right: "RH"
    EOG_vertical_left: "LV"
    EOG_r_l_diff: "L-R"
  EMG:
    LLEG_power: "LL"
    RLEG_power: "RL"
    CHEMG_power: "Chin"
  ECG:
    ECG_heart_rate: "HR"
    ECG_SDNN: "SDNN"
    ECG_rmssd: "HRV"
